Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 40

Metrics/BlockLength:
  Max: 35

AllCops:
  TargetRubyVersion: 2.6

Metrics/AbcSize:
  Max: 50

Style/ClassVars:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false

Lint/Void:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 20

Metrics/ClassLength:
  Max: 400